import { Pet, PetDataSource, Organization } from './base';

// Mock organizations
const mockOrganizations: Record<string, Organization> = {
  'mock-shelter-1': {
    id: 'mock-shelter-1',
    name: 'Happy Tails Rescue',
    email: 'adopt@happytails.org',
    phone: '(555) 123-4567',
    address: '123 Main Street, Austin, TX 78701',
    city: 'Austin',
    state: 'TX',
    website: 'https://happytails.org',
    adoptionPolicy: 'All pets are spayed/neutered, vaccinated, and microchipped before adoption. We require a home visit and adoption application. Adoption fee covers all veterinary care.',
    hours: 'Mon-Fri: 10am-6pm, Sat-Sun: 11am-5pm',
  },
  'mock-shelter-2': {
    id: 'mock-shelter-2',
    name: 'Second Chance Animal Shelter',
    email: 'info@secondchance.org',
    phone: '(555) 987-6543',
    address: '456 Oak Avenue, Dallas, TX 75201',
    city: 'Dallas',
    state: 'TX',
    website: 'https://secondchanceshelter.org',
    adoptionPolicy: 'We are a foster-based rescue. All animals live in foster homes until adoption. Meet-and-greets can be scheduled after your application is approved.',
    hours: 'By appointment only',
  },
};

export class MockAdapter implements PetDataSource {
  private pets: Pet[] = [
      // --- DOGS ---
      {
        id: '1',
        name: 'Bandit',
        breed: 'Blue Heeler Mix',
        status: 'Available',
        sex: 'Male',
        age: '2 years',
        description: 'Hi, I\'m Bandit! I\'m full of energy and absolutely love frisbees. I need an active owner who can keep up with me on adventures!',
        imageUrl: 'https://images.unsplash.com/photo-1517849845537-4d257902454a?auto=format&fit=crop&w=800',
        images: [
          'https://images.unsplash.com/photo-1517849845537-4d257902454a?auto=format&fit=crop&w=800',
          'https://images.unsplash.com/photo-1587300003388-59208cc962cb?auto=format&fit=crop&w=800',
          'https://images.unsplash.com/photo-1530281700549-e82e7bf110d6?auto=format&fit=crop&w=800',
        ],
        tags: ['Dog', 'High Energy', 'Hiking Buddy'],
        daysInShelter: 5,
        location: 'Austin, TX',
        energyLevel: 'High',
        size: 'Medium',
        color: 'Blue / White',
        coatLength: 'Short',
        compatibility: { kids: true, dogs: true, cats: false, otherAnimals: null },
        health: { spayedNeutered: true, vaccinated: true, microchipped: true, specialNeeds: false },
        houseTrained: true,
        goodOnLeash: true,
        organization: mockOrganizations['mock-shelter-1'],
      },
      {
        id: '4',
        name: 'Rex',
        breed: 'German Shepherd',
        status: 'Available',
        sex: 'Male',
        age: '9 years',
        description: 'Hey there, I\'m Rex. I\'m a gentle grandpa looking for a quiet porch to relax on. I\'ve got plenty of wisdom and love to share!',
        imageUrl: 'https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?auto=format&fit=crop&w=800',
        images: [
          'https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?auto=format&fit=crop&w=800',
          'https://images.unsplash.com/photo-1568572933382-74d440642117?auto=format&fit=crop&w=800',
          'https://images.unsplash.com/photo-1553882809-a4f57e59501d?auto=format&fit=crop&w=800',
        ],
        tags: ['Dog', 'Senior', 'Chill'],
        daysInShelter: 145,
        location: 'Austin, TX',
        energyLevel: 'Low',
        size: 'Large',
        color: 'Black / Tan',
        coatLength: 'Medium',
        compatibility: { kids: true, dogs: true, cats: true, otherAnimals: true },
        health: { spayedNeutered: true, vaccinated: true, microchipped: true, specialNeeds: false },
        houseTrained: true,
        goodOnLeash: true,
        organization: mockOrganizations['mock-shelter-1'],
      },
      {
        id: '5',
        name: 'Pip',
        breed: 'Jack Russell',
        status: 'Available',
        sex: 'Male',
        age: '1 year',
        description: 'I\'m Pip and I may be small, but I\'m mighty! I absolutely love to dig - your backyard will never be the same!',
        imageUrl: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&w=800',
        images: [
          'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&w=800',
          'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&w=800',
        ],
        tags: ['Dog', 'Small', 'High Energy'],
        daysInShelter: 20,
        location: 'Dallas, TX',
        energyLevel: 'High',
        size: 'Small',
        color: 'White / Brown',
        coatLength: 'Short',
        compatibility: { kids: false, dogs: true, cats: false, otherAnimals: false },
        health: { spayedNeutered: true, vaccinated: true, microchipped: true, specialNeeds: false },
        houseTrained: false,
        goodOnLeash: false,
        organization: mockOrganizations['mock-shelter-2'],
      },
      {
        id: '7',
        name: 'Thor',
        breed: 'Husky',
        status: 'Available',
        sex: 'Male',
        age: '3 years',
        description: 'Awoooo! I\'m Thor and I love to talk! I\'ll sing you the song of my people every day. Hope you like conversation!',
        imageUrl: 'https://images.unsplash.com/photo-1560743641-691c7705cf63?auto=format&fit=crop&w=800',
        images: [
          'https://images.unsplash.com/photo-1560743641-691c7705cf63?auto=format&fit=crop&w=800',
          'https://images.unsplash.com/photo-1605568427561-40dd23c2acea?auto=format&fit=crop&w=800',
          'https://images.unsplash.com/photo-1547407139-3c921a66005c?auto=format&fit=crop&w=800',
          'https://images.unsplash.com/photo-1590419690008-905895e8fe0d?auto=format&fit=crop&w=800',
        ],
        tags: ['Dog', 'Vocal', 'Sheds a Lot'],
        daysInShelter: 60,
        location: 'Austin, TX',
        energyLevel: 'High',
        size: 'Large',
        color: 'Gray / White',
        coatLength: 'Long',
        compatibility: { kids: true, dogs: true, cats: false, otherAnimals: false },
        health: { spayedNeutered: true, vaccinated: true, microchipped: true, specialNeeds: false },
        houseTrained: true,
        goodOnLeash: false,
        organization: mockOrganizations['mock-shelter-1'],
      },
      {
        id: '9',
        name: 'Daisy',
        breed: 'Pit Bull Mix',
        status: 'Available',
        sex: 'Female',
        age: '4 years',
        description: 'Hi, I\'m Daisy! I\'m a giant marshmallow who thinks I\'m a lap dog. I promise I\'ll keep you warm on the couch!',
        imageUrl: 'https://images.unsplash.com/photo-1561037404-61cd46aa615b?auto=format&fit=crop&w=800',
        images: [
          'https://images.unsplash.com/photo-1561037404-61cd46aa615b?auto=format&fit=crop&w=800',
          'https://images.unsplash.com/photo-1541599540903-216a46ca1dc0?auto=format&fit=crop&w=800',
          'https://images.unsplash.com/photo-1518717758536-85ae29035b6d?auto=format&fit=crop&w=800',
        ],
        tags: ['Dog', 'Couch Potato', 'Strong'],
        daysInShelter: 10,
        location: 'Austin, TX',
        energyLevel: 'Low',
        size: 'Large',
        color: 'Brindle',
        coatLength: 'Short',
        compatibility: { kids: true, dogs: true, cats: true, otherAnimals: null },
        health: { spayedNeutered: true, vaccinated: true, microchipped: true, specialNeeds: false },
        houseTrained: true,
        goodOnLeash: true,
        organization: mockOrganizations['mock-shelter-1'],
      },
      {
        id: '10',
        name: 'Chip',
        breed: 'Beagle',
        status: 'Available',
        sex: 'Male',
        age: '5 years',
        description: 'I\'m Chip, and I come with my best buddy Dale! We\'re a bonded pair and need to be adopted together. Double the love!',
        imageUrl: 'https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?auto=format&fit=crop&w=800',
        images: [
          'https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?auto=format&fit=crop&w=800',
          'https://images.unsplash.com/photo-1505628346881-b72b27e84530?auto=format&fit=crop&w=800',
        ],
        tags: ['Dog', 'Bonded Pair', 'Vocal'],
        daysInShelter: 35,
        location: 'Dallas, TX',
        energyLevel: 'Moderate',
        size: 'Medium',
        color: 'Tricolor',
        coatLength: 'Short',
        compatibility: { kids: true, dogs: true, cats: false, otherAnimals: false },
        health: { spayedNeutered: true, vaccinated: true, microchipped: true, specialNeeds: false },
        houseTrained: true,
        goodOnLeash: true,
        organization: mockOrganizations['mock-shelter-2'],
      },
      {
        id: '11',
        name: 'Bear',
        breed: 'Newfoundland',
        status: 'Pending',
        sex: 'Male',
        age: '5 years',
        description: 'I\'m Bear, a gentle giant who loves water! Take me to the lake and I\'ll be your best swimming buddy forever.',
        imageUrl: 'https://images.unsplash.com/photo-1544568100-847a948585b9?auto=format&fit=crop&w=800',
        images: [
          'https://images.unsplash.com/photo-1544568100-847a948585b9?auto=format&fit=crop&w=800',
          'https://images.unsplash.com/photo-1477884213360-7e9d7dcc1e48?auto=format&fit=crop&w=800',
          'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=800',
        ],
        tags: ['Dog', 'Large', 'Chill'],
        daysInShelter: 2,
        location: 'Austin, TX',
        energyLevel: 'Low',
        size: 'Extra Large',
        color: 'Black',
        coatLength: 'Long',
        compatibility: { kids: true, dogs: true, cats: true, otherAnimals: true },
        health: { spayedNeutered: true, vaccinated: true, microchipped: true, specialNeeds: false },
        houseTrained: true,
        goodOnLeash: true,
        organization: mockOrganizations['mock-shelter-1'],
      },
      {
        id: '12',
        name: 'Coco',
        breed: 'Poodle Mix',
        status: 'Available',
        sex: 'Female',
        age: '2 years',
        description: 'Hi, I\'m Coco! I\'m hypoallergenic and super smart. I already know lots of tricks and I\'m ready to learn more with you!',
        imageUrl: 'https://images.unsplash.com/photo-1591769225440-811ad7d6eca6?auto=format&fit=crop&w=800',
        images: [
          'https://images.unsplash.com/photo-1591769225440-811ad7d6eca6?auto=format&fit=crop&w=800',
          'https://images.unsplash.com/photo-1535930891776-0c2dfb7fda1a?auto=format&fit=crop&w=800',
        ],
        tags: ['Dog', 'Small', 'Smart'],
        daysInShelter: 12,
        location: 'Austin, TX',
        energyLevel: 'Moderate',
        size: 'Small',
        color: 'Apricot',
        coatLength: 'Medium',
        compatibility: { kids: true, dogs: true, cats: true, otherAnimals: true },
        health: { spayedNeutered: true, vaccinated: true, microchipped: true, specialNeeds: false },
        houseTrained: true,
        goodOnLeash: true,
        organization: mockOrganizations['mock-shelter-1'],
      },
      // --- CATS ---
      {
        id: '2',
        name: 'Luna',
        breed: 'Siamese',
        status: 'Available',
        sex: 'Female',
        age: '1 year',
        description: 'Meow! I\'m Luna, and yes, I\'m a vocal princess who demands attention. But I\'ll repay you with endless purrs and cuddles!',
        imageUrl: 'https://images.unsplash.com/photo-1513245543132-31f507417b26?auto=format&fit=crop&w=800',
        images: [
          'https://images.unsplash.com/photo-1513245543132-31f507417b26?auto=format&fit=crop&w=800',
          'https://images.unsplash.com/photo-1555685812-4b943f1cb0eb?auto=format&fit=crop&w=800',
          'https://images.unsplash.com/photo-1592194996308-7b43878e84a6?auto=format&fit=crop&w=800',
        ],
        tags: ['Cat', 'Vocal', 'Indoor Only'],
        daysInShelter: 45,
        location: 'Austin, TX',
        energyLevel: 'Moderate',
        size: 'Small',
        color: 'Seal Point',
        coatLength: 'Short',
        compatibility: { kids: true, dogs: false, cats: true, otherAnimals: null },
        health: { spayedNeutered: true, vaccinated: true, microchipped: true, specialNeeds: false },
        houseTrained: true,
        declawed: false,
        organization: mockOrganizations['mock-shelter-1'],
      },
      {
        id: '3',
        name: 'Oliver',
        breed: 'Orange Tabby',
        status: 'Available',
        sex: 'Male',
        age: '5 years',
        description: 'Hey, I\'m Oliver! I love lasagna and sleeping in sunbeams. My perfect day is napping, eating, and getting belly rubs.',
        imageUrl: 'https://images.unsplash.com/photo-1574158622682-e40e69881006?auto=format&fit=crop&w=800',
        images: [
          'https://images.unsplash.com/photo-1574158622682-e40e69881006?auto=format&fit=crop&w=800',
          'https://images.unsplash.com/photo-1573865526739-10659fec78a5?auto=format&fit=crop&w=800',
          'https://images.unsplash.com/photo-1495360010541-f48722b34f7d?auto=format&fit=crop&w=800',
        ],
        tags: ['Cat', 'Chill', 'Food Motivated'],
        daysInShelter: 8,
        location: 'Dallas, TX',
        energyLevel: 'Low',
        size: 'Medium',
        color: 'Orange',
        coatLength: 'Short',
        compatibility: { kids: true, dogs: true, cats: true, otherAnimals: true },
        health: { spayedNeutered: true, vaccinated: true, microchipped: true, specialNeeds: false },
        houseTrained: true,
        declawed: false,
        specialDiet: true,
        organization: mockOrganizations['mock-shelter-2'],
      },
      {
        id: '6',
        name: 'Mittens',
        breed: 'Tuxedo Cat',
        status: 'Available',
        sex: 'Female',
        age: '8 weeks',
        description: 'Mew mew! I\'m Mittens, a tiny kitten with a BIG personality! I\'m ready to play, explore, and steal your heart!',
        imageUrl: 'https://images.unsplash.com/photo-1561948955-570b270e7c36?auto=format&fit=crop&w=800',
        images: [
          'https://images.unsplash.com/photo-1561948955-570b270e7c36?auto=format&fit=crop&w=800',
          'https://images.unsplash.com/photo-1606214174585-fe31582dc6ee?auto=format&fit=crop&w=800',
          'https://images.unsplash.com/photo-1596854407944-bf87f6fdd49e?auto=format&fit=crop&w=800',
          'https://images.unsplash.com/photo-1583795128727-6ec3642408f8?auto=format&fit=crop&w=800',
        ],
        tags: ['Cat', 'Kitten', 'Playful'],
        daysInShelter: 3,
        location: 'Austin, TX',
        energyLevel: 'High',
        size: 'Small',
        color: 'Black / White',
        coatLength: 'Short',
        compatibility: { kids: true, dogs: true, cats: true, otherAnimals: null },
        health: { spayedNeutered: false, vaccinated: true, microchipped: false, specialNeeds: false },
        houseTrained: false,
        declawed: false,
        organization: mockOrganizations['mock-shelter-1'],
      },
      {
        id: '8',
        name: 'Shadow',
        breed: 'Black Cat',
        status: 'Available',
        sex: 'Male',
        age: '2 years',
        description: 'I\'m Shadow, a mysterious ninja cat. You\'ll never see me coming, but I promise I\'m the most loyal companion once you earn my trust.',
        imageUrl: 'https://images.unsplash.com/photo-1557246565-8a3d3ab5d7f6?auto=format&fit=crop&w=800',
        images: [
          'https://images.unsplash.com/photo-1557246565-8a3d3ab5d7f6?auto=format&fit=crop&w=800',
          'https://images.unsplash.com/photo-1511044568932-338cba0ad803?auto=format&fit=crop&w=800',
        ],
        tags: ['Cat', 'Shy', 'Independent'],
        daysInShelter: 90,
        location: 'Austin, TX',
        energyLevel: 'Low',
        size: 'Medium',
        color: 'Black',
        coatLength: 'Short',
        compatibility: { kids: false, dogs: false, cats: true, otherAnimals: false },
        health: { spayedNeutered: true, vaccinated: true, microchipped: true, specialNeeds: false },
        houseTrained: true,
        declawed: false,
        organization: mockOrganizations['mock-shelter-1'],
      },
      {
        id: '13',
        name: 'Simba',
        breed: 'Maine Coon Mix',
        status: 'Available',
        sex: 'Male',
        age: '3 years',
        description: 'Roar! I\'m Simba, a majestic lion of a cat. I\'m very fluffy and I demand to be brushed like the royalty I am.',
        imageUrl: 'https://images.unsplash.com/photo-1533738363-b7f9aef128ce?auto=format&fit=crop&w=800',
        images: [
          'https://images.unsplash.com/photo-1533738363-b7f9aef128ce?auto=format&fit=crop&w=800',
          'https://images.unsplash.com/photo-1615497001839-b0a0eac3274c?auto=format&fit=crop&w=800',
          'https://images.unsplash.com/photo-1606567595334-d39972c85dfd?auto=format&fit=crop&w=800',
        ],
        tags: ['Cat', 'Large', 'Fluffy'],
        daysInShelter: 15,
        location: 'Dallas, TX',
        energyLevel: 'Moderate',
        size: 'Large',
        color: 'Brown Tabby',
        coatLength: 'Long',
        compatibility: { kids: true, dogs: true, cats: true, otherAnimals: true },
        health: { spayedNeutered: true, vaccinated: true, microchipped: true, specialNeeds: false },
        houseTrained: true,
        declawed: false,
        organization: mockOrganizations['mock-shelter-2'],
      },
      {
        id: '14',
        name: 'Bella',
        breed: 'Calico',
        status: 'Available',
        sex: 'Female',
        age: '6 years',
        description: 'I\'m Bella, the queen of any house I live in. I tolerate humans... and occasionally allow them to pet me. You\'re welcome.',
        imageUrl: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=800',
        images: [
          'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=800',
          'https://images.unsplash.com/photo-1478098711619-5ab0b478d6e6?auto=format&fit=crop&w=800',
          'https://images.unsplash.com/photo-1494256997604-768d1f608cac?auto=format&fit=crop&w=800',
        ],
        tags: ['Cat', 'Independent', 'Sassy'],
        daysInShelter: 55,
        location: 'Austin, TX',
        energyLevel: 'Low',
        size: 'Medium',
        color: 'Calico',
        coatLength: 'Medium',
        compatibility: { kids: false, dogs: false, cats: false, otherAnimals: false },
        health: { spayedNeutered: true, vaccinated: true, microchipped: true, specialNeeds: false },
        houseTrained: true,
        declawed: false,
        organization: mockOrganizations['mock-shelter-1'],
      },
  ];

  async getAllPets(): Promise<Pet[]> {
    // Simulate network delay
    await new Promise((resolve) => setTimeout(resolve, 500));
    // Mark all mock pets as having real descriptions (not synthetic)
    return this.pets.map(pet => ({
      ...pet,
      shelterNotes: pet.description, // Use description as shelter notes
      isSyntheticDescription: false, // Mock data simulates real shelter descriptions
    }));
  }

  async getPet(id: string): Promise<Pet | null> {
    await new Promise((resolve) => setTimeout(resolve, 300));
    const pet = this.pets.find((p) => p.id === id);
    if (!pet) return null;
    return {
      ...pet,
      shelterNotes: pet.description,
      isSyntheticDescription: false,
    };
  }
}
